### ISSUE TITLE
indexing gets stuck

### ISSUE THREAD

**Issue by bambix1977** [splitbrain/dokuwiki-plugin-searchindex#31]
I've been trying to move some namespaces but now the indexer gets stuck at a random page when rebuilding the index.
restarting the rebuild just starts the same process and then it stops at a different page.
Using dokiwiki on iis8 in 2012 r2 vm.
Cannot figure out where it's going wrong, the contents of the pages is rather small so I doubt it's the actual content of the page.
I've tried doing hard refreshes etc.

**Comment by splitbrain** [comment]
Do you get any error messages anywhere? Like in the JavaScript console? In your webserver/php logs? There is no way to figure out what's happing without any further info.

**Comment by bambix1977** [comment]
I ended up canceling continuously, each time I cancelled it would go one page further next time I rebuilt the index, So basically I rebuilt the index 60 times and now it seems to work again. Looking back in the iis logs doesn't give much of an error, mostly because the indexer would just get stuck and I can only see the canceling. So for now it works, thnx.

**Comment by bambix1977** [comment]
Do want to add a big Thank you and keep up the good work!
