### ISSUE TITLE
Index isn´t updating automatically

### ISSUE THREAD

**Issue by Almi14** [splitbrain/dokuwiki-plugin-searchindex#39]
Hi there,

I have already successfully used the plugin on another Windows installation. There the index was also always updated automatically so that the manual update was not necessary or only rarely necessary.

Now I moved the Wiki some time ago. Also a Windows installation and with the Bitnami Dokuwiki Stack. 

The index is no longer updated automatically, a manual update is always necessary. Either via this plugin or via php call the indexer.php. Both works fine. Does anyone have an idea?

I have already completely deleted the index and rebuilt it. But if you make a change to a page or create new pages they are not found it is necessary to manually update the index again. 

Best Regards!

**Comment by splitbrain** [comment]
See https://www.dokuwiki.org/indexer for debugging problems with the indexer and also make sure your template actually calls the indexer. please report back with more details.
